# Docker Compose file for Django and React application

services:
  backend:
    build:
      context: ./djangobnb
      dockerfile: Dockerfile
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./djangobnb:/app
    env_file:
      - ./djangobnb/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./djangobnb/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./djangobnb/frontend:/app
    stdin_open: true
    tty: true

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: djangobnb
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
