# Generated by Django 4.2.20 on 2025-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='uploads/properties/'),
        ),
    ]
